[tool.poetry]
name = "cfdmod"
version = "0.1.0"
description = "Tools for analysis of CFD cases"
authors = ["Waine Oliveira Jr <waine@aerosim.io>", "Pablo Penas <pablo@aerosim.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <3.13"
numpy = "^1.25.2"
notebook = "^7.0.3"
scipy = "^1.11.2"
matplotlib = "^3.7.3"
pandas = "^2.1.0"
pydantic = "^2.3.0"

[tool.poetry.group.altimetry]
optional = true

[tool.poetry.group.altimetry.dependencies]
trimesh = "^3.23.5"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.7.0"}
isort = {extras = ["jupyter"], version = "^5.12.0"}
autoflake = "^2.2.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx-book-theme = "^1.0.1"
myst-parser = "^2.0.0"
sphinx-autobuild = "^2021.3.14"
nbsphinx = "^0.9.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '(\.pyi?$|\.ipynb)'
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99
src_paths = ["cfdmod", "tests", "notebooks"]
skip_glob = ["**/__init__.py"] # avoid circular imports

[tool.ruff]
fixable = ["ALL"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 99
target-version = "py310"
