[tool.poetry]
name = "cfdmod"
version = "0.1.0"
description = "Tools for analysis of CFD cases"
authors = ["Waine Oliveira Jr <waine@aerosim.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.7.0"}
isort = {extras = ["jupyter"], version = "^5.12.0"}
autoflake = "^2.2.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx-book-theme = "^1.0.1"
myst-parser = "^2.0.0"
sphinx-autobuild = "^2021.3.14"
nbsphinx = "^0.9.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
