"""Loader for frozen legacy-parity golden values.

The archive is generated by ``fixtures/tests/dynamics/_generate_goldens.py``
while ``cfdmod.hfpi`` still exists. Tests load these instead of importing the
(now deleted) legacy module, so the characterization guard survives the
one-shot cutover. Regenerate only if an input builder intentionally changes.
"""

from __future__ import annotations

import pathlib

import numpy as np

_PATH = (
    pathlib.Path(__file__).parents[2] / "fixtures" / "tests" / "dynamics" / "legacy_goldens.npz"
)
_CACHE: dict[str, np.ndarray] | None = None


def golden(key: str) -> np.ndarray:
    """Return the frozen legacy output stored under ``key``."""
    global _CACHE
    if _CACHE is None:
        with np.load(_PATH) as data:
            _CACHE = {k: data[k] for k in data.files}
    return _CACHE[key]
