name: Release artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_LNAS }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          pip install -U poetry
          poetry cache clear --all pypi
          poetry install --with docs

      - name: Build the project with Poetry
        run: poetry build

      - name: List files in dist directory
        run: ls -al ./dist

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF##*/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${GITHUB_REF##*/v}"

      - name: Sphinx build
        run: |
          sudo apt-get install -y pandoc
          cd docs
          poetry run make html  # Build HTML docs
          cd ..
          zip -r docs-version-${{ env.VERSION }}.zip docs/build/html

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          file: |
            ./dist/cfdmod-${{ env.VERSION }}.tar.gz
            ./dist/cfdmod-${{ env.VERSION }}-py3-none-any.whl
            docs-version-${{ env.VERSION }}.zip
