name: Build and Deploy artifacts

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-upload:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_LNAS }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install --with vtk,lnas,geometry

      - name: Build the project with Poetry
        run: poetry build

      - name: List files in dist directory
        run: ls -al ./dist

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF#refs/heads/release/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Zip
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/cfdmod-${{ env.VERSION }}.tar.gz
          asset_name: ./dist/cfdmod-release-${{ env.VERSION }}.tar.gz
          asset_content_type: application/zip

      - name: Upload Release Asset Wheel
        id: upload-release-asset-wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/cfdmod-${{ env.VERSION }}-py3-none-any.whl
          asset_name: ./dist/cfdmod-release-${{ env.VERSION }}-py3-none-any.whl
          asset_content_type: application/zip
