name: Linting Workflow

on:
  pull_request:
  push:
    branches: [main]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install --only dev

      - name: Run Linters
        run: |
          poetry run black .
          poetry run isort .

      - name: Check for changes after linting
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Warning: Code must be formatted!" >&2
            git status --porcelain
            exit 1
          else
            echo "No formatting issues detected."
          fi
