name: Linting Workflow

on:
  pull_request:
  push:
    branches: [main]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install black[jupyter] isort ruff

      - name: Run isort
        run: isort --check-only .

      - name: Run black
        run: black --config ./pyproject.toml --check .

      - name: Run ruff
        run: ruff check .