name: Testing Pipeline

on:
  pull_request:
  push:
    branches: [main]

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tox-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv
          uv venv

      - name: Install dependencies with uv
        run: uv pip install .[vtk,lnas,geometry]

      - name: Run Tox
        run: uv run tox
